name: Node.js CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
